# Generated by Django 3.2 on 2022-04-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220401_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_ip',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like_ip',
            field=models.TextField(null=True),
        ),
    ]
