# Generated by Django 3.2 on 2022-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_image_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_ip',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_ip',
            field=models.TextField(default=''),
        ),
    ]
